version: "0.2"
ignorePaths:
  - "node_modules"
  - "/.eslintignore"
  - "/.git"
  - "/.gitignore"
  - "/.husky"
  - "/.markdownlint.yaml" # spellchecker: disable-line
  - "/.prettierrc.yaml"
  - "/.vscode"
  - "/build"
  - "/coverage"
  - "/cspell.dictionary_swiss-german_project.txt"
  - "/docs/_site"
  - "/docs/.sass-cache"
  - "/docs/.jekyll-cache"
  - "/docs/assets/screenshots/**/*.xcf"
  - "/docs/browserconfig.xml" # spellchecker: disable-line
  - "/docs/safari-pinned-tab.svg"
  - "/resources/icon.svg"
  - "/settings/licenses.js"
dictionaryDefinitions:
  [
    {
      name: "de-ch-project",
      path: "./cspell.dictionary_swiss-german_project.txt"
    }
  ]
dictionaries: ["!de-ch"]
words:
  - andreas
  - buymeacoffee
  - cbor
  - codacy
  - commitlint
  - fitbit
  - gettext
  - msgid
  - msgstr
  - nygard
  - otpauth
  - remigius
  - stylelint
  - totp
ignoreWords:
  - conventionalcommits
  - infile
  - nuintun
  - qrcode
  - rseidelsohn
  - tsdoc
import: ["@cspell/dict-de-ch/cspell-ext.json"]
flagWords:
  - topt # spellchecker: disable-line
overrides:
  - filename: "**/i18n/de-DE.po"
    dictionaries: ["!!de-ch", "de-ch-project"]
  - filename: "docs/collections/_app_de/**/*.md"
    dictionaries: ["!!de-ch", "de-ch-project", "!en_us"]
