version: "0.2"
ignorePaths:
  - "node_modules"
  - "/.eslintignore"
  - "/.git"
  - "/.gitignore"
  - "/.husky"
  - "/.markdownlint.yaml" # spellchecker: disable-line
  - "/.prettierrc.yaml"
  - "/.vscode"
  - "/build"
  - "/coverage"
  - "/resources/icon.svg"
  - "/settings/licenses.js"
dictionaryDefinitions: []
dictionaries: ["!de-ch"]
words:
  - andreas
  - cbor
  - commitlint
  - fitbit
  - gettext
  - msgid
  - msgstr
  - otpauth
  - remigius
  - stylelint
  - totp
ignoreWords:
  - nuintun
  - qrcode
  - rseidelsohn
  - tsdoc
import: ["@cspell/dict-de-ch/cspell-ext.json"]
flagWords:
  - topt # spellchecker: disable-line
overrides:
  - filename: "**/i18n/de-DE.po"
    dictionaries: ["!!de-ch"]
