version: "0.2"
ignorePaths:
  - "node_modules"
  - "/.eslintignore"
  - "/.git"
  - "/.gitignore"
  - "/.husky"
  - "/.markdownlint.yaml" # spellchecker: disable-line
  - "/.prettierrc.yaml"
  - "/.vscode"
  - "/build"
  - "/coverage"
  - "/settings/licenses.js"
dictionaryDefinitions: []
dictionaries: ["!de-ch"]
words:
  - andreas
  - commitlint
  - fitbit
  - gettext
  - msgid
  - msgstr
  - remigius
  - stylelint
  - totp
ignoreWords:
  - rseidelsohn
  - tsdoc
import: ["@cspell/dict-de-ch/cspell-ext.json"]
flagWords: []
overrides:
  - filename: "**/i18n/de-DE.po"
    dictionaries: ["!!de-ch"]
